# ~/.config/mpd/mpd.conf

music_directory    "/home/eren/Music"
playlist_directory "/home/eren/.config/mpd/playlists"
db_file            "/home/eren/.config/mpd/database"
log_file           "/home/eren/.config/mpd/log"
pid_file           "/home/eren/.config/mpd/pid"
state_file         "/home/eren/.config/mpd/state"
sticker_file       "/home/eren/.config/mpd/sticker.sql"

# Connection settings
bind_to_address    "/tmp/mpd_socket"
bind_to_address    "127.0.0.1"
port               "6600"    

# Audio Output
audio_output {
    type    "pipewire"
    name    "PipeWire"
}
